kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: alertmanager-data-pvc 
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true" 
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-east1-d